dataset:
  name: "RadioML2018"
  num_classes: 24

model:
  variant: "Medium"
  d_model: 32
  nhead: 8
  num_layers: 4
  dim_feedforward: 64
  k: 16
  s: 8
  dtanh: true
  linattn: true

training:
  epochs: 300
  batch_size: 512
  learning_rate: 0.001
  patience: 100